### PR TITLE
Update versions and fix breaking changes

### PR DESCRIPTION
**Pull request by RusticFlare**
Update the versions to work with Kotest 1.5

### CODE REVIEW

**Comment by RusticFlare** [comment]
I think the build failure is a false negative. The only failing tests are called `failing test` and are `1 shouldBe 2`

**Comment by sksamuel** [comment]
I've kicked the build off again.

**Comment by sksamuel** [comment]
I think you can make this work by marking the sample specs as private, and then deleting the project config.

**Comment by RusticFlare** [comment]
@sksamuel Thank you for the tips. That got it working ✅

**Comment by sksamuel** [comment]
1.1.0 released.

**Pull request merged**
